// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAicofZ7tNQdt35ZlbUjpfRBL_IPNwn7QU',
    appId: '1:333677946586:web:a74856bba81fd66af967e3',
    messagingSenderId: '333677946586',
    projectId: 'cubitauthwithkeepuserloginedin',
    authDomain: 'cubitauthwithkeepuserloginedin.firebaseapp.com',
    storageBucket: 'cubitauthwithkeepuserloginedin.appspot.com',
    measurementId: 'G-Y810S3EZKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYfbAh1zn2K7ebwRLwpYf7uX3IRNGwy88',
    appId: '1:333677946586:android:52f83d749e78e781f967e3',
    messagingSenderId: '333677946586',
    projectId: 'cubitauthwithkeepuserloginedin',
    storageBucket: 'cubitauthwithkeepuserloginedin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVoIVHqKCRCtJYfNMAV1FMM12ri-W2vo0',
    appId: '1:333677946586:ios:7c2bd82dbd38a4fff967e3',
    messagingSenderId: '333677946586',
    projectId: 'cubitauthwithkeepuserloginedin',
    storageBucket: 'cubitauthwithkeepuserloginedin.appspot.com',
    iosBundleId: 'com.example.keepuserloginedinwithsherdprefranses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVoIVHqKCRCtJYfNMAV1FMM12ri-W2vo0',
    appId: '1:333677946586:ios:2e5a85bb4f404e53f967e3',
    messagingSenderId: '333677946586',
    projectId: 'cubitauthwithkeepuserloginedin',
    storageBucket: 'cubitauthwithkeepuserloginedin.appspot.com',
    iosBundleId: 'com.example.keepuserloginedinwithsherdprefranses.RunnerTests',
  );
}
